2017-12-28 21:33:40,558 [Thread-2:1452] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 34, in index
    archive_list = Article.objects.distinct_date()
AttributeError: 'Manager' object has no attribute 'distinct_date'
2017-12-28 21:37:59,718 [Thread-2:5504] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 34, in index
    archive_list = Article.objects.distinct_date()
AttributeError: 'Manager' object has no attribute 'distinct_date'
2017-12-28 21:45:37,861 [Thread-2:580] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 34, in index
    archive_list = Article.objects.distinct_date()
  File "D:\django\django课件\项目\blogProject\myblog\models.py", line 69, in distinct_date
    date = date['date_publish'].strftime('%Y年%m文章存档')
UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: Illegal byte sequence
2017-12-28 21:47:59,733 [Thread-2:880] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 34, in index
    archive_list = Article.objects.distinct_date()
  File "D:\django\django课件\项目\blogProject\myblog\models.py", line 69, in distinct_date
    date = date['date_publish'].strftime('%Y/%m文章存档')
UnicodeEncodeError: 'locale' codec can't encode character '\u6587' in position 5: Illegal byte sequence
2017-12-28 21:52:43,161 [Thread-2:8368] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 38, in index
    return render(request, 'myblog/index.html', locals())
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Anacoda\lib\site-packages\django\template\engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Anacoda\lib\site-packages\django\template\engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Anacoda\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 233, in compile_nodelist
    return parser.parse()
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 242, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 698, in __init__
    self.args_check(filter_name, filter_func, args)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 773, in args_check
    (name, alen - dlen, plen))
django.template.exceptions.TemplateSyntaxError: slice requires 2 arguments, 1 provided
2017-12-28 21:56:08,407 [Thread-2:2088] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 34, in index
    archive_list = Article.objects.distinct_date()
  File "D:\django\django课件\项目\blogProject\myblog\models.py", line 69, in distinct_date
    date = date['date_publish'].strftime('%Y年%m月')
UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: Illegal byte sequence
2017-12-28 22:00:40,190 [Thread-2:1968] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 34, in index
    archive_list = Article.objects.distinct_date()
  File "D:\django\django课件\项目\blogProject\myblog\models.py", line 70, in distinct_date
    date = date['date_publish'].strftime('%Y/%m文章归档')
UnicodeEncodeError: 'locale' codec can't encode character '\u6587' in position 5: Illegal byte sequence
2017-12-28 22:08:16,609 [Thread-2:3972] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 34, in index
    archive_list = Article.objects.distinct_date()
  File "D:\django\django课件\项目\blogProject\myblog\models.py", line 71, in distinct_date
    date = date['date_publish'].strftime('%Y/%m文章归档')
UnicodeEncodeError: 'locale' codec can't encode character '\u6587' in position 5: Illegal byte sequence
2017-12-28 22:16:09,737 [Thread-4:8368] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 34, in index
    archive_list = Article.objects.distinct_date()
  File "D:\django\django课件\项目\blogProject\myblog\models.py", line 71, in distinct_date
    date = date['date_publish'].strftime('%Y/%m文章归档')
UnicodeEncodeError: 'locale' codec can't encode character '\u6587' in position 5: Illegal byte sequence
2017-12-28 22:17:34,786 [Thread-2:9052] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 34, in index
    archive_list = Article.objects.distinct_date()
  File "D:\django\django课件\项目\blogProject\myblog\models.py", line 71, in distinct_date
    date = date['date_publish'].strftime('%Y/%m文章归档')
UnicodeEncodeError: 'locale' codec can't encode character '\u6587' in position 5: Illegal byte sequence
2017-12-28 22:23:37,792 [Thread-6:9752] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/archive
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 128, in archive
    return render(request, 'myblog/archive.html', locals())
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 201, in render
    template = context.template.engine.get_template(template_name)
  File "D:\Anacoda\lib\site-packages\django\template\engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Anacoda\lib\site-packages\django\template\engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Anacoda\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 233, in compile_nodelist
    return parser.parse()
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 574, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'static'. Did you forget to register or load this tag?
2017-12-28 22:33:57,478 [Thread-20:6668] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 38, in index
    return render(request, 'myblog/index.html', locals())
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "D:\Anacoda\lib\site-packages\django\template\engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Anacoda\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 233, in compile_nodelist
    return parser.parse()
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 238, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
2017-12-28 22:57:46,271 [Thread-2:2296] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 39, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{'art_id': ''}' not found. 1 pattern(s) tried: ['myblog/detail/(?P<art_id>\\d+)/$']
2017-12-28 22:59:45,550 [Thread-8:10424] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 39, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{'art_id': ''}' not found. 1 pattern(s) tried: ['myblog/detail/(?P<art_id>\\d+)/$']
2017-12-28 23:09:36,123 [Thread-2:9632] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 39, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['myblog/detail/(?P<art_id>\\d+)/$']
2017-12-29 08:31:44,797 [Thread-2:9564] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2017-12-29 08:31:44,996 [Thread-3:6184] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-12-29 08:49:04,217 [Thread-2:8296] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/archive
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myblog.views.archive didn't return an HttpResponse object. It returned None instead.
2017-12-29 08:52:16,785 [Thread-2:2428] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/archive
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myblog.views.archive didn't return an HttpResponse object. It returned None instead.
2017-12-29 08:52:19,659 [Thread-3:1136] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/archive
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myblog.views.archive didn't return an HttpResponse object. It returned None instead.
2017-12-29 08:52:23,985 [Thread-29:9452] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/archive
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myblog.views.archive didn't return an HttpResponse object. It returned None instead.
2017-12-29 08:54:26,721 [Thread-2:4532] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/archive
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 49, in archive
    article_list = Article.objects.filter(date_publish__icoantains= year + '-' + month)
  File "D:\Anacoda\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 794, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 812, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1187, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1081, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1099, in try_transform
    (name, lhs.output_field.__class__.__name__))
django.core.exceptions.FieldError: Unsupported lookup 'icoantains' for DateTimeField or join on the field not permitted.
2017-12-29 10:16:32,644 [Thread-15:8800] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 44, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-29 10:18:02,669 [Thread-21:6320] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 44, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-29 12:08:00,773 [Thread-27:10852] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 44, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-29 12:54:13,104 [Thread-2:10968] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 44, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-29 12:54:58,790 [Thread-6:6516] [django.request:152] [base:get_response] [WARNING]- Not Found: /mylog/index
2017-12-29 12:55:04,009 [Thread-7:8392] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 44, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-29 13:02:18,937 [Thread-2:11328] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 44, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-29 13:02:33,212 [Thread-4:12076] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 44, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-29 13:04:00,326 [Thread-2:12060] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 44, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-29 13:06:50,687 [Thread-2:11612] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2017-12-29 13:06:59,237 [Thread-4:3324] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 44, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-29 13:25:52,207 [Thread-26:5556] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/detail/
2017-12-29 13:26:30,630 [Thread-35:7132] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/detail/id=8
2017-12-29 13:27:07,530 [Thread-2:3736] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/detail/id=8
2017-12-29 13:27:57,749 [Thread-2:11592] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/detail/id=8
2017-12-29 13:28:05,774 [Thread-9:11892] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/detail/id=7
2017-12-29 13:30:39,499 [Thread-2:8412] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/detail/id=7
2017-12-29 13:30:43,943 [Thread-9:11412] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/detail/id=6
2017-12-29 13:32:18,661 [Thread-2:9732] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 44, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '(8,)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['myblog/detail/\\d+/$']
2017-12-29 13:39:41,990 [Thread-69:1856] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/6/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myblog.views.article_detail didn't return an HttpResponse object. It returned None instead.
2017-12-29 13:40:40,682 [Thread-75:4668] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/7/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myblog.views.article_detail didn't return an HttpResponse object. It returned None instead.
2017-12-29 17:06:45,636 [Thread-154:12172] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/
2017-12-29 17:24:11,706 [Thread-41:11424] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2017-12-30 08:13:11,432 [Thread-44:5796] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2017-12-30 08:13:11,693 [Thread-45:4448] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-12-30 08:13:15,510 [Thread-46:12048] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 34, in index
    archive_list = Article.objects.distinct_date()
  File "D:\django\django课件\项目\blogProject\myblog\models.py", line 70, in distinct_date
    print(date['date_publish'])
OSError: [Errno 22] Invalid argument
2017-12-30 09:24:06,192 [Thread-2:11448] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/3/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myblog.views.article_detail didn't return an HttpResponse object. It returned None instead.
2017-12-30 09:24:14,373 [Thread-3:5608] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/detail
2017-12-30 09:24:26,171 [Thread-35:88] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/8/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myblog.views.article_detail didn't return an HttpResponse object. It returned None instead.
2017-12-30 09:25:00,146 [Thread-2:2152] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/8/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view myblog.views.article_detail didn't return an HttpResponse object. It returned None instead.
2017-12-30 09:25:38,636 [Thread-2:12428] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/8/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 77, in article_detail
    return render(request, 'myblog/detail.html', {"article": article, 'comments': comments})
UnboundLocalError: local variable 'comments' referenced before assignment
2017-12-30 09:57:54,222 [Thread-7:3920] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/
2017-12-30 10:06:25,337 [Thread-50:5624] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/
2017-12-30 10:07:34,677 [Thread-40:12232] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/6/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 78, in article_detail
    return render(request, 'myblog/detail.html', locals())
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 10:08:07,593 [Thread-41:7148] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/6/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 78, in article_detail
    return render(request, 'myblog/detail.html', locals())
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 10:08:11,095 [Thread-42:11376] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/4/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 78, in article_detail
    return render(request, 'myblog/detail.html', locals())
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 10:09:40,340 [Thread-48:11604] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/4/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 78, in article_detail
    return render(request, 'myblog/detail.html', locals())
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'comment_post' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 10:35:13,720 [Thread-2:1532] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/4/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 79, in article_detail
    return render(request, 'myblog/detail.html', locals())
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for '' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 10:48:17,471 [Thread-2:12304] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/detail/4/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 86, in article_detail
    return render(request, 'myblog/detail.html', locals())
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'comment_post' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 10:59:50,515 [Thread-46:13252] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/comment_post
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 90, in comment_post
    date_publish = comments.cleaned_data['time'],
KeyError: 'time'
2017-12-30 11:00:34,575 [Thread-24:3340] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/comment_post
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 89, in comment_post
    user = request.session.username,
AttributeError: 'SessionStore' object has no attribute 'username'
2017-12-30 11:12:51,821 [Thread-2:12304] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/comment_post
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 89, in comment_post
    user = request.session.username,
AttributeError: 'SessionStore' object has no attribute 'username'
2017-12-30 13:10:55,791 [Thread-24:9024] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/comment_post
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 119, in comment_post
    return render(request, 'myblog/failure.html', {'reason': comments.errors})
NameError: name 'comments' is not defined
2017-12-30 13:33:02,343 [Thread-46:4692] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/comment_post
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 107, in comment_post
    user = request.session.username,
AttributeError: 'SessionStore' object has no attribute 'username'
2017-12-30 13:41:07,844 [Thread-111:11956] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/comment_post
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 107, in comment_post
    user = request.session.username,
AttributeError: 'SessionStore' object has no attribute 'username'
2017-12-30 13:46:17,373 [Thread-24:3652] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/comment_post
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 108, in comment_post
    article_id=comment_form.cleaned_data['comment'],
KeyError: 'comment'
2017-12-30 14:09:28,557 [Thread-2:13012] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 41, in index
    article_comment_list = [Article.objects.get(pk=comment['article']) for comment in comment_count_list]
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 41, in <listcomp>
    article_comment_list = [Article.objects.get(pk=comment['article']) for comment in comment_count_list]
  File "D:\Anacoda\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
myblog.models.DoesNotExist: Article matching query does not exist.
2017-12-30 14:18:15,096 [Thread-2:11652] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 43, in index
    article_comment_list=[Article.objects.get(pk=comment['article'])]
  File "D:\Anacoda\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
myblog.models.DoesNotExist: Article matching query does not exist.
2017-12-30 14:18:28,817 [Thread-2:4772] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 43, in index
    article_comment_list=[Article.objects.get(pk=comment['article'])]
  File "D:\Anacoda\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
myblog.models.DoesNotExist: Article matching query does not exist.
2017-12-30 14:18:53,791 [Thread-4:7056] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 43, in index
    article_comment_list=[Article.objects.get(pk=comment['article'])]
  File "D:\Anacoda\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
myblog.models.DoesNotExist: Article matching query does not exist.
2017-12-30 14:19:10,533 [Thread-6:12388] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2017-12-30 14:19:20,161 [Thread-7:7772] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 43, in index
    article_comment_list=[Article.objects.get(pk=comment['article'])]
  File "D:\Anacoda\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
myblog.models.DoesNotExist: Article matching query does not exist.
2017-12-30 14:25:05,909 [Thread-40:6200] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2017-12-30 14:26:20,067 [Thread-41:2268] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 49, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 14:26:29,351 [Thread-42:2152] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 49, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 14:37:16,773 [Thread-2:10136] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 47, in index
    archive_click_list = Article.objects.filter(articles)
  File "D:\Anacoda\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 794, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 812, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1130, in build_filter
    arg, value = filter_expr
ValueError: too many values to unpack (expected 2)
2017-12-30 15:18:15,312 [Thread-2:3336] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 49, in index
    arts = Article.objects.filter(is_recomment=True)
  File "D:\Anacoda\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 794, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anacoda\lib\site-packages\django\db\models\query.py", line 812, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1133, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1019, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Anacoda\lib\site-packages\django\db\models\sql\query.py", line 1327, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'is_recomment' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2017-12-30 15:19:40,792 [Thread-9:3776] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2017-12-30 15:20:14,079 [Thread-17:8012] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2017-12-30 15:23:52,283 [Thread-24:10720] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 15:24:14,337 [Thread-30:12052] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 15:24:17,138 [Thread-31:11136] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 15:25:41,178 [Thread-36:12096] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-12-30 15:26:35,506 [Thread-39:6828] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['myblog/detail/(\\d+)/$']
2017-12-30 15:27:42,352 [Thread-42:8300] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['myblog/detail/(\\d+)/$']
2017-12-30 15:27:55,231 [Thread-2:12116] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['myblog/detail/(\\d+)/$']
2017-12-30 15:28:06,416 [Thread-3:2200] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['myblog/detail/(\\d+)/$']
2017-12-30 15:49:13,787 [Thread-2:8104] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'link_detail' with arguments '(6,)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['myblog/link_detail$']
2017-12-30 15:49:34,082 [Thread-2:4028] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'link_detail' with arguments '(6,)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['myblog/link_detail$']
2017-12-30 15:52:32,431 [Thread-2:1076] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/index
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 59, in index
    return render(request, 'myblog/index.html', context)
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Anacoda\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Anacoda\lib\site-packages\django\urls\resolvers.py", line 389, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for 'link_detail' with arguments '(6,)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['myblog/link_detail$']
2017-12-30 15:53:01,453 [Thread-5:100] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/link_detail
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: link_detail() missing 1 required positional argument: 'id'
2017-12-30 15:53:42,956 [Thread-6:96] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/link_detail
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: link_detail() missing 1 required positional argument: 'id'
2017-12-30 15:53:47,828 [Thread-7:2360] [django.request:152] [base:get_response] [WARNING]- Not Found: /myblog/link_detail/1
2017-12-30 15:54:09,818 [Thread-2:1712] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/link_detail/1
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 80, in link_detail
    return render(request, 'myblog/link_detail.html', {"links": links})
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'Links' object is not iterable
2017-12-30 15:57:09,190 [Thread-6:2800] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/link_detail/1
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 80, in link_detail
    return render(request, 'myblog/link_detail.html', {"links": links})
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'Links' object is not iterable
2017-12-30 16:00:15,399 [Thread-3:12936] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/link_detail/1/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 80, in link_detail
    return render(request, 'myblog/link_detail.html', {"links": links})
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'Links' object is not iterable
2017-12-30 16:00:19,270 [Thread-4:2004] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/link_detail/1/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 80, in link_detail
    return render(request, 'myblog/link_detail.html', {"links": links})
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'Links' object is not iterable
2017-12-30 16:02:15,523 [Thread-5:2148] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/link_detail/6/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 80, in link_detail
    return render(request, 'myblog/link_detail.html', {"links": links})
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'Links' object is not iterable
2017-12-30 16:04:17,600 [Thread-6:4224] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/link_detail/6/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 80, in link_detail
    return render(request, 'myblog/link_detail.html', {"links": links})
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'Links' object is not iterable
2017-12-30 16:04:50,705 [Thread-2:9780] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /myblog/link_detail/6/
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anacoda\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django\django课件\项目\blogProject\myblog\views.py", line 81, in link_detail
    return render(request, 'myblog/link_detail.html', locals())
  File "D:\Anacoda\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Anacoda\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Anacoda\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Anacoda\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Anacoda\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'Links' object is not iterable
